media: src/content/media
content:
  - name: Obras
    label: Obras de art
    type: collection
    path: src/content/obras
    view: 
      fields: ["titlo","categoria","serie","fecha","medio", "descript", "ancho", "largo", "foto", "galeria", "body"]
    fields:
      - name: titlo
        label: Titlo de la obra
        type: string
      - name: categoria
        label: Categorias a las que pertenece
        type: select
        options:
          values: [ Pintura, Escultura ]
          multiple: true
          creatable: true
      - name: serie
        label: Serie de obras en la que se enmarca
        type: select
        options:
          values: [ Locurillas, Inglaterra, B&W ]
          multiple: true
          creatable: true
      - name: fecha
        label: Fecha de creación
        type: date
        options:
          format: yyyy-MM-dd
          min: 2001-01-01
      - name: medio
        label: Materiales blablabla
        type: select
        options:
          values: [ "Óleo sobre tela" ]
          creatable: true
      - name: descript
        label: Descripción
        type: string
      - name: ancho
        label: Medida de ancho
        type: number
      - name: largo
        label: Medida de largo
        type: number
      - name: foto
        label: Foto principal de la obra
        type: image
      - name: galeria
        label: Galeria detalles obra
        type: image
        options:
          multiple:
            max: 10
      - name: body
        label: Body
        type: rich-text
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    view: 
      fields: ["titulo", "cover", "body", ]
    fields: 
      - name: titulo
        label: titulo
        type: string
      - name: cover
        label: Foto principal
        type: image
      - name: body
        label: Body
        type: rich-text