media: src/content/media
content:
  - name: Obras
    label: Obras de art
    type: collection
    path: src/content/obras
    view: 
      fields: ["titulo","categoria","serie","fecha","medio", "descript", "ancho", "alto", "foto", "galeria", "body", "displayPriority", "disponible"]
    fields:
      - name: titulo
        label: Titulo de la obra
        type: string
      - name: categoria
        label: Categorias a las que pertenece
        type: select
        options:
          values: [ Pintura, Escultura ]
          creatable: true
        default: Pintura 
      - name: serie
        label: Serie de obras en la que se enmarca
        type: select
        options:
          values: [ Locurillas, Inglaterra, B&W ]
          creatable: true
      - name: fecha
        label: Fecha de creación
        type: date
        options:
          format: yyyy-MM-dd
          min: 2001-01-01
      - name: medio
        label: Materiales blablabla
        type: select
        options:
          values: [ "Óleo sobre tela" , "Acrílico sobre tela"]
          creatable: true
      - name: descript
        label: Descripción
        type: string
      - name: ancho
        label: Medida de ancho
        type: number
      - name: alto
        label: Medida de alto
        type: number
      - name: foto
        label: Foto principal de la obra
        type: image
      - name: galeria
        label: Galeria detalles obra
        type: image
        options:
          multiple:
            max: 10
      - name: body
        label: Body
        type: rich-text
      - name: displayPriority
        label: Prioridad al mostrar cuando empatan (1 es primero) 
        type: number
      - name: disponible
        label: Disponible para vender
        type: boolean
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    view: 
      fields: ["titulo", "cover", "body", ]
    fields: 
      - name: titulo
        label: titulo
        type: string
      - name: cover
        label: Foto principal
        type: image
      - name: body
        label: Body
        type: rich-text