media: src/content/media
content:
  - name: Obras
    label: Obras de art
    type: collection
    path: src/content/obras
    view: 
      fields: ["titulo","categoria","serie","fecha","medio", "descript", "ancho", "alto", "foto", "galeria", "body", "displayPriority", "disponible"]
    fields:
      - name: titulo
        label: Titulo de la obra
        type: string
      - name: categoria
        label: Categorias
        type: select
        options:
          values: [ Pintura, Escultura ]
          creatable: true
        default: Pintura 
      - name: serie
        label: Serie
        type: select
        options:
          values: [ Locurillas, Inglaterra, B&W ]
          creatable: true
      - name: fecha
        label: Fecha de creación
        type: date
        options:
          format: yyyy-MM-dd
          min: 2001-01-01
      - name: medio
        label: Materiales
        type: select
        options:
          values: [ "Óleo sobre tela" , "Acrílico sobre tela"]
          creatable: true
      - name: descript
        label: Descripción
        type: string
      - name: ancho
        label: Ancho
        type: number
      - name: alto
        label: Alto
        type: number
      - name: foto
        label: Foto principal
        type: image
      - name: galeria
        label: Galería
        type: image
        options:
          multiple:
            max: 10
      - name: body
        label: Body
        type: rich-text
      - name: displayPriority
        label: Prioridad
        type: number
      - name: disponible
        label: Disponible
        type: boolean
        default: false
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    view: 
      fields: ["titulo", "cover", "body", ]
    fields: 
      - name: titulo
        label: titulo
        type: string
      - name: cover
        label: Foto principal
        type: image
      - name: body
        label: Body
        type: rich-text